apiVersion: v1
kind: ReplicationController
metadata:
  name: openstf-reaper
  labels:
    app: openstf-reaper
spec:
  replicas: 1
  selector:
    app: openstf-reaper
  template:
    metadata:
      labels:
        app: openstf-reaper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openstf-reaper
        image: openstf/stf:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        command: ["stf"]
        args:
          - reaper
          - "dev"
          - --connect-push
          - "tcp://openstf-triproxy-dev:7270"
          - --connect-sub
          - "tcp://openstf-triproxy-app:7150"
          - --heartbeat-timeout
          -  "30000"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
          - configMapRef:
              name: openstf-config
        env:
        - name: RETHINKDB_ENV_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: rethinkdb-secret
              key: AUTHKEY
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
