apiVersion: v1
kind: ReplicationController
metadata:
  name: openstf-provider-proxy
  labels:
    app: openstf-provider-proxy
spec:
  replicas: 1
  selector:
    app: openstf-provider-proxy
  template:
    metadata:
      labels:
        app: openstf-provider-proxy
    spec:
      containers:
      - name: openstf-provider-proxy
        image: registry:5443/openstf/openstf-provider-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: proxy
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
      imagePullSecrets:
      - name: nexus3-docker-secret
