apiVersion: v1
kind: ReplicationController
metadata:
  name: openstf-auth
spec:
  replicas: 1
  selector:
    app: openstf-auth
  template:
    metadata:
      labels:
        app: openstf-auth
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openstf-auth
        image: openstf/stf:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: auth
        command: ["stf"]
        args:
          - "auth-mock"
          - --secret
          - "$(SECRET)"
          - --port
          - "3000"
          - --app-url
          - "$(OPENSTF_BASE_URL)"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
          - configMapRef:
              name: openstf-config
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: openstf-app-secret
              key: SECRET
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
