apiVersion: v1
kind: Service
metadata:
  name: openstf-triproxy-app
spec:
  ports:
   - port: 7150
     targetPort: 7150
     name: bind-pub
   - port: 7160
     targetPort: 7160
     name: bind-dealer
   - port: 7170
     targetPort: 7170
     name: bind-pull  
  selector:
    app: openstf-triproxy-app