apiVersion: v1
kind: ReplicationController
metadata:
  name: openstf-storage-plugin-image
  labels:
    app: openstf-storage-plugin-image
spec:
  replicas: 1
  selector:
    app: openstf-storage-plugin-image
  template:
    metadata:
      labels:
        app: openstf-storage-plugin-image
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openstf-storage-plugin-image
        image: openstf/stf:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: image
        command: ["stf"]
        args:
          - "storage-plugin-image"
          - --port
          - "3000"
          - --storage-url
          - "$(OPENSTF_BASE_URL)"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
          - configMapRef:
              name: openstf-config
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
