apiVersion: v1
kind: ReplicationController
metadata:
  name: openstf-triproxy-dev
  labels:
    app: openstf-triproxy-dev
spec:
  replicas: 1
  selector:
    app: openstf-triproxy-dev
  template:
    metadata:
      labels:
        app: openstf-triproxy-dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openstf-triproxy-dev
        image: openstf/stf:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 7250
            name: bind-pub
          - containerPort: 7260
            name: bind-dealer
          - containerPort: 7270
            name: bind-pull
        command: ["stf"]
        args:
          - triproxy
          - "dev"
          - --bind-pub
          - "tcp://*:7250"
          - --bind-dealer
          - "tcp://*:7260"
          - --bind-pull
          - "tcp://*:7270"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
