apiVersion: v1
kind: Service
metadata:
  name: openstf-storage-temp
spec:
  ports:
   - port: 3000
     targetPort: tmp-storage
     name: tmp-storage
  selector:
    app: openstf-storage-temp