apiVersion: v1
kind: ReplicationController
metadata:
  name: openstf-storage-temp
  labels:
    app: openstf-storage-temp
spec:
  replicas: 1
  selector:
    app: openstf-storage-temp
  template:
    metadata:
      labels:
        app: openstf-storage-temp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openstf-storage-temp
        image: openstf/stf:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: tmp-storage
        command: ["stf"]
        args:
          - "storage-temp"
          - --port
          - "3000"
          - --save-dir
          - "/data"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /data
          name: openstf-storage-temp-data
      volumes:
        - name: openstf-storage-temp-data
          persistentVolumeClaim:
            claimName: openstf-storage-temp-data-claim
